#! /bin/sh

export PATH="$HOME/bin:$PATH"

xset s off
xset -dpms
xset s noblank
xrdb merge ~/.Xresources &

if [ -x $HOME/bin/dual_monitor ];then
    dual_monitor
fi

bspc config focus_follows_pointer true
bspc config top_padding 27

bspc config focused_border_color "#555566"
bspc config normal_border_color "#555566"

bspc config border_width 2
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config window_gap 10
bspc config split_ratio 0.5

bspc config pointer_modifier mod1
bspc config border_radius 5

pgrep -x sxhkd > /dev/null || sxhkd &
source $HOME/.config/bspwm/startup-programs
