#! /bin/sh

export PATH="$HOME/bin:$PATH"
export WALLPAPER="/home/augustin64/Pictures/wallpaper/lGDDYk0.jpg"

#autostart apps
pgrep -x sxhkd > /dev/null || sxhkd &

# gtk themes and term colorsheme
cp -r ~/Public/theme\ and\ icons/bsp/.gtkrc-2.0 ~/ &
cp -r ~/Public/theme\ and\ icons/bsp/settings.ini ~/.config/gtk-3.0/ &
xrdb merge ~/.Xresources &

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.

if [ -x $HOME/bin/dual_monitor ];then
    dual_monitor
fi

# keyboard settings

numlockx &
setxkbmap fr &

picom &

# polybar 
cp -r ~/Public/poly/bsp/polybar ~/.config/ &
~/.config/polybar/launch.sh &


bspc config focus_follows_pointer true

bspc config top_padding 20

# borders
bspc config focused_border_color "#353b45"
bspc config normal_border_color "#282c34"
bspc config border_width 2
bspc config borderless_monocle true

#gaps 
bspc config gapless_monocle false
bspc config window_gap 15
bspc config split_ratio 0.50

$HOME/.config/bspwm/startup-programs
