#!/bin/sh

numlockx &
setxkbmap fr &
picom &

"$HOME/.config/polybar/launch.sh" &

nm-applet &
alacritty &
"$HOME/bin/bspwm-wallpaper-changer" --source local --sleep 300 --path /home/augustin64/Pictures/wallpaper/ &

if pidof -x "redshift" >/dev/null; then
   echo "redshift already running"
else
    redshift -l 43.1749:5.2251 &
fi

libinput-gestures-setup start
