#!/bin/sh

source "$HOME/.config/dotfiles/load.sh"

numlockx &
setxkbmap fr &
xcmenu &

pgrep -x picom       > /dev/null || picom &
pgrep -x alacritty   > /dev/null || alacritty &
pgrep -x nm-applet   > /dev/null || nm-applet &
pgrep -x polybar     > /dev/null || "$HOME/.config/polybar/launch.sh" &
pgrep -x redshift    > /dev/null || redshift -l 43.1749:5.2251 &

setwall "$DEFAULT_WALL" &

if [[ "$CHANGE_WALL" -eq 1 ]]; then
   "$HOME/bin/bspwm-wallpaper-changer" --sleep "$WALL_UPDATE_FREQ" --path "$WALLPAPERS_PATH" &
fi;

libinput-gestures-setup start &
"$HOME/.config/dotfiles/autostart.sh" &
