#!/bin/sh

source "$HOME/.config/dotfiles/load.sh"

numlockx &
setxkbmap fr &
picom &
nm-applet &
alacritty &

if pidof -x "polybar" >/dev/null; then
   echo "polybar already running"
else
   "$HOME/.config/polybar/launch.sh" &
fi;

setwall "$DEFAULT_WALL" 

if [[ "$CHANGE_WALL" -eq 1 ]]; then
   "$HOME/bin/bspwm-wallpaper-changer" --sleep "$WALL_UPDATE_FREQ" --path "$WALLPAPERS_PATH" &
fi;

if pidof -x "redshift" >/dev/null; then
   echo "redshift already running"
else
    redshift -l 43.1749:5.2251 &
fi

libinput-gestures-setup start &
"$HOME/.config/dotfiles/autostart.sh" &
